version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-package:
          name: <<parameters.os>>-unit-tests
          node_version: latest
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
            exclude:
              - os: windows
                node_version: lts
              - os: windows
                node_version: maintenance
          exclude:
            - os: windows
              node_version: lts
            - os: windows
              node_version: maintenance
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          sign: true
          requires:
            - node-latest
            - node-12
          filters:
            branches:
              only: master
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
