version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          sign: true
          requires:
            - node-latest
            - node-12
          filters:
            branches:
              only: master
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
